export const fontFamily = 'PlusJakartaSans, "Segoe UI", system-ui, -apple-system, sans-serif';
export const colors = {
    white: '#FFFFFF',
    bg: '#FFFFFF',
    bgGray: '#F6F7F8',
    tabBar: '#F4F5F6',
    tabPill: '#DDDDDF',
    ink: '#151516',
    inkStrong: '#151516',
    inkSecondary: '#737373',
    inkMuted: '#A1A1A2',
    inkPlaceholder: '#B0B0B5',
    inkLight: '#C7C7CC',
    promoPink: '#FFE0E8',
    promoPeach: '#FEE5E1',
    promoYellow: '#FEECD7',
    promoMint: '#E3F0EA',
    promoBlue: '#CEF0F5',
    promoEnd: '#FFFEFE',
    brandStart: '#DA60BF',
    brandPink: '#F160A9',
    brandRed: '#F65A90',
    brandPeach: '#F98872',
    brandEnd: '#F3AB5A',
    btnStart: '#F65991',
    btnEnd: '#F79E5C',
    btnBlack: '#151516',
    btnGray: '#F0F0F2',
    btnGrayText: '#1A1A1A',
    divider: '#ECECEE',
    border: '#E5E5E8',
    fab: '#ECEDEE',
    emptyTile: '#F6F6F6',
    orgBadge: '#E0E0E2',
    nearCapacity: '#B45309',
    nearCapacityBg: '#FEF3C7',
    waitlistBlue: '#2563EB',
    waitlistBg: '#EFF6FF',
    detailBg: '#090720',
    detailCard: '#1E2230',
    detailText: '#FFFFFF',
    detailMuted: '#AEB0B5',
} as const;
export const fonts = {
    regular: 'PlusJakartaSans',
    medium: 'PlusJakartaSans',
    semibold: 'PlusJakartaSans',
    bold: 'PlusJakartaSans',
} as const;
export const spacing = {
    page: 15,
    small: 8,
    row: 12,
    section: 24,
    card: 16,
} as const;
export const radius = {
    sheet: 28,
    card: 16,
    input: 16,
    pill: 999,
    cover: 12,
} as const;
export const typeScale = {
    wordmark: 24,
    largeTitle: 30,
    section: 19,
    nearby: 19,
    viewAll: 16,
    emptyTitle: 16,
    emptyDesc: 14,
    date: 16,
    cardTitle: 16,
    host: 12,
    meta: 14,
    tab: 12,
    small: 11,
} as const;
