export const colors = {
    white: '#FFFFFF',
    bg: '#FFFFFF',
    bgGray: '#F6F7F8',
    tabBar: '#F4F5F6',
    ink: '#1A1A1A',
    inkSecondary: '#6B6B70',
    inkMuted: '#9B9BA0',
    inkPlaceholder: '#B0B0B5',
    inkLight: '#C7C7CC',
    promoPink: '#FEE2EA',
    promoYellow: '#FDEDD9',
    promoBlue: '#CCEEF4',
    promoEnd: '#FFFEFE',
    brandStart: '#E8448A',
    brandMid: '#F47060',
    brandEnd: '#E8B84D',
    btnBlack: '#111111',
    btnGray: '#F0F0F2',
    btnGrayText: '#1A1A1A',
    divider: '#ECECEE',
    border: '#E5E5E8',
    nearCapacity: '#D97706',
    nearCapacityBg: '#FEF3C7',
    waitlistBlue: '#2563EB',
    waitlistBg: '#EFF6FF',
    detailBg: '#0D0B20',
    detailCard: '#1E2230',
    detailText: '#FFFFFF',
    detailMuted: '#9CA3AF',
} as const;
export const fonts = {
    regular: 'Inter_400Regular',
    medium: 'Inter_500Medium',
    semibold: 'Inter_600SemiBold',
    bold: 'Inter_700Bold',
} as const;
export const spacing = {
    page: 16,
    small: 8,
    row: 12,
    section: 24,
    card: 16,
} as const;
export const radius = {
    sheet: 28,
    card: 16,
    input: 16,
    pill: 999,
    cover: 14,
} as const;
export const typeScale = {
    largeTitle: 34,
    title: 28,
    section: 22,
    cardTitle: 20,
    body: 16,
    meta: 14,
    small: 12,
} as const;
